import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🧹 Limpiando base de datos...');
  
  // Limpiar en orden correcto por las foreign keys
  await prisma.movimientoInventario.deleteMany();
  await prisma.inventarioActual.deleteMany();
  await prisma.producto.deleteMany();
  await prisma.categoria.deleteMany();
  await prisma.distribuidor.deleteMany();
  
  console.log('✅ Base de datos limpia');

  // Crear categorías
  console.log('📁 Creando categorías...');
  const categorias = await Promise.all([
    prisma.categoria.create({ data: { nombre: 'Guantes y Protección', descripcion: 'Guantes de todo tipo y equipos de protección personal' } }),
    prisma.categoria.create({ data: { nombre: 'Jeringas y Agujas', descripcion: 'Jeringas desechables y agujas de todo tipo' } }),
    prisma.categoria.create({ data: { nombre: 'Medicamentos Veterinarios', descripcion: 'Medicamentos, antibióticos y tratamientos' } }),
    prisma.categoria.create({ data: { nombre: 'Equipos de Fumigación', descripcion: 'Fumigadoras y accesorios' } }),
    prisma.categoria.create({ data: { nombre: 'Ferretería', descripcion: 'Puntillas, alambre, herramientas' } }),
    prisma.categoria.create({ data: { nombre: 'Semillas', descripcion: 'Semillas de hortalizas y pastos' } }),
    prisma.categoria.create({ data: { nombre: 'Equipos de Montura', descripcion: 'Frenos, riendas, sillas y accesorios equinos' } }),
    prisma.categoria.create({ data: { nombre: 'Accesorios Mascotas', descripcion: 'Collares, correas y accesorios para perros y gatos' } }),
    prisma.categoria.create({ data: { nombre: 'Calzado', descripcion: 'Botas de trabajo y calzado' } }),
    prisma.categoria.create({ data: { nombre: 'Sales y Minerales', descripcion: 'Sales mineralizadas y suplementos' } }),
    prisma.categoria.create({ data: { nombre: 'Vacunas', descripcion: 'Vacunas para animales' } }),
    prisma.categoria.create({ data: { nombre: 'Alimentos Mascotas', descripcion: 'Alimentos para perros y gatos' } }),
    prisma.categoria.create({ data: { nombre: 'Control de Plagas', descripcion: 'Insecticidas, raticidas y control de plagas' } }),
    prisma.categoria.create({ data: { nombre: 'Accesorios Varios', descripcion: 'Llaveros, navajas, linternas y otros' } }),
    prisma.categoria.create({ data: { nombre: 'Tubería y Riego', descripcion: 'Accesorios de tubería y riego' } }),
    prisma.categoria.create({ data: { nombre: 'Lazos y Cuerdas', descripcion: 'Lazos, cuerdas y cordones' } }),
    prisma.categoria.create({ data: { nombre: 'Avicultura', descripcion: 'Bebederos, comederos y accesorios para aves' } }),
  ]);

  const catMap: Record<string, number> = {};
  categorias.forEach(c => { catMap[c.nombre] = c.id; });

  // Crear distribuidores
  console.log('🚚 Creando distribuidores...');
  const distribuidores = await Promise.all([
    prisma.distribuidor.create({ data: { nombre: 'Paisas', contacto: 'Contacto Paisas' } }),
    prisma.distribuidor.create({ data: { nombre: 'San Antonio', contacto: 'Contacto San Antonio' } }),
    prisma.distribuidor.create({ data: { nombre: 'Agro Oriente', contacto: 'Contacto Agro Oriente' } }),
    prisma.distribuidor.create({ data: { nombre: 'INDAGRO', contacto: 'Contacto INDAGRO' } }),
    prisma.distribuidor.create({ data: { nombre: 'Agro Paisa', contacto: 'Contacto Agro Paisa' } }),
    prisma.distribuidor.create({ data: { nombre: 'Mil Herrajes', contacto: 'Contacto Mil Herrajes' } }),
    prisma.distribuidor.create({ data: { nombre: 'Unionagro', contacto: 'Contacto Unionagro' } }),
    prisma.distribuidor.create({ data: { nombre: 'Uniferragro', contacto: 'Contacto Uniferragro' } }),
    prisma.distribuidor.create({ data: { nombre: 'Indurruedas', contacto: 'Contacto Indurruedas' } }),
    prisma.distribuidor.create({ data: { nombre: 'Químicos', contacto: 'Contacto Químicos' } }),
    prisma.distribuidor.create({ data: { nombre: 'Vetiagro', contacto: 'Contacto Vetiagro' } }),
    prisma.distribuidor.create({ data: { nombre: 'Alianza', contacto: 'Contacto Alianza' } }),
    prisma.distribuidor.create({ data: { nombre: 'Sogamoso', contacto: 'Contacto Sogamoso' } }),
    prisma.distribuidor.create({ data: { nombre: 'Agrocampo', contacto: 'Contacto Agrocampo' } }),
    prisma.distribuidor.create({ data: { nombre: 'El Toro', contacto: 'Contacto El Toro' } }),
    prisma.distribuidor.create({ data: { nombre: 'Talabartería', contacto: 'Contacto Talabartería' } }),
    prisma.distribuidor.create({ data: { nombre: 'Superagro', contacto: 'Contacto Superagro' } }),
  ]);

  const distMap: Record<string, number> = {};
  distribuidores.forEach(d => { distMap[d.nombre.toLowerCase()] = d.id; });

  // Función para mapear distribuidor
  const getDistId = (dist: string | null): number | null => {
    if (!dist) return null;
    const d = dist.toLowerCase().trim();
    if (d.includes('paisa') && !d.includes('agro')) return distMap['paisas'];
    if (d.includes('san') && d.includes('ant')) return distMap['san antonio'];
    if (d.includes('agro') && d.includes('oriente')) return distMap['agro oriente'];
    if (d.includes('indagro')) return distMap['indagro'];
    if (d.includes('agro') && d.includes('paisa')) return distMap['agro paisa'];
    if (d.includes('herraje')) return distMap['mil herrajes'];
    if (d.includes('union') && d.includes('agro')) return distMap['unionagro'];
    if (d.includes('unifer')) return distMap['uniferragro'];
    if (d.includes('indu') || d.includes('rueda')) return distMap['indurruedas'];
    if (d.includes('quim')) return distMap['químicos'];
    if (d.includes('veti')) return distMap['vetiagro'];
    if (d.includes('alianza')) return distMap['alianza'];
    if (d.includes('sogamoso')) return distMap['sogamoso'];
    if (d.includes('agrocampo')) return distMap['agrocampo'];
    if (d.includes('toro')) return distMap['el toro'];
    if (d.includes('talabarteria')) return distMap['talabartería'];
    if (d.includes('super')) return distMap['superagro'];
    return null;
  };

  // Función para determinar categoría por nombre del producto
  const getCatId = (nombre: string): number => {
    const n = nombre.toLowerCase();
    if (n.includes('guante')) return catMap['Guantes y Protección'];
    if (n.includes('jeringa') || n.includes('aguja')) return catMap['Jeringas y Agujas'];
    if (n.includes('vacuna')) return catMap['Vacunas'];
    if (n.includes('fumigador') || n.includes('bomba')) return catMap['Equipos de Fumigación'];
    if (n.includes('puntilla') || n.includes('alambre') || n.includes('grapa') || n.includes('machete') || n.includes('macheta') || n.includes('lima') || n.includes('cuchillo')) return catMap['Ferretería'];
    if (n.includes('semilla') || n.includes('zanahoria') || n.includes('perejil') || n.includes('pimenton') || n.includes('cilantro') || n.includes('pipino') || n.includes('tomate') || n.includes('acelga') || n.includes('espinaca') || n.includes('cebolla') || n.includes('brachiaria') || n.includes('maiz')) return catMap['Semillas'];
    if (n.includes('freno') || n.includes('rienda') || n.includes('sinch') || n.includes('pretal') || n.includes('herradura') || n.includes('arcio') || n.includes('baticola') || n.includes('apero') || n.includes('catabra')) return catMap['Equipos de Montura'];
    if (n.includes('collar') || n.includes('cuello') || n.includes('correa') || n.includes('bozal') || n.includes('pechera') || n.includes('isabelino')) return catMap['Accesorios Mascotas'];
    if (n.includes('bota')) return catMap['Calzado'];
    if (n.includes('sal ') || n.includes('ganasal') || n.includes('premezcla') || n.includes('mineral')) return catMap['Sales y Minerales'];
    if (n.includes('chunky') || n.includes('ringo') || n.includes('pedegree') || n.includes('italcan') || n.includes('galleta') || n.includes('delidog') || n.includes('menu natural') || n.includes('qdican')) return catMap['Alimentos Mascotas'];
    if (n.includes('campeon') || n.includes('cucaracha') || n.includes('trampa') || n.includes('raid') || n.includes('hormiga') || n.includes('hormitox') || n.includes('sicario') || n.includes('tiza china') || n.includes('pegante rato') || n.includes('cinta mosca') || n.includes('tabla') || n.includes('gel cucaracha') || n.includes('lorsban') || n.includes('neftalina')) return catMap['Control de Plagas'];
    if (n.includes('llavero') || n.includes('navaja') || n.includes('linterna') || n.includes('gorra') || n.includes('poncho') || n.includes('sombrero') || n.includes('estuche') || n.includes('forro') || n.includes('candado')) return catMap['Accesorios Varios'];
    if (n.includes('union ') || n.includes('codo') || n.includes('acople') || n.includes('teflon') || n.includes('manguera')) return catMap['Tubería y Riego'];
    if (n.includes('lazo') || n.includes('cuerda') || n.includes('cordon')) return catMap['Lazos y Cuerdas'];
    if (n.includes('bebedero') || n.includes('comedero')) return catMap['Avicultura'];
    // Por defecto medicamentos
    return catMap['Medicamentos Veterinarios'];
  };

  // Datos del inventario real
  const inventarioReal: Array<{ nombre: string; cantidad: number | null; precioCompra: number | null; distribuidor: string | null; precioVenta: number | null }> = [
    { nombre: 'guantes gloves rojo y negro', cantidad: 15, precioCompra: 3000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'guantes de cuero largo', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'guantes de cuero corto', cantidad: 3, precioCompra: 5000, distribuidor: null, precioVenta: 10500 },
    { nombre: 'guantes guadaña tela blanco y negro', cantidad: 14, precioCompra: 3000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'campeon cucarachas', cantidad: 11, precioCompra: 400, distribuidor: 'paisas', precioVenta: 1000 },
    { nombre: 'jeringas 5 ml', cantidad: 100, precioCompra: 250, distribuidor: null, precioVenta: 500 },
    { nombre: 'jeringas 2 ml', cantidad: 124, precioCompra: 250, distribuidor: null, precioVenta: 450 },
    { nombre: 'jeringas 10 ml', cantidad: 132, precioCompra: 300, distribuidor: null, precioVenta: 1000 },
    { nombre: 'jeringas 20 ml', cantidad: 103, precioCompra: 420, distribuidor: null, precioVenta: 1000 },
    { nombre: 'jeringas 3ml', cantidad: 58, precioCompra: 250, distribuidor: null, precioVenta: 500 },
    { nombre: 'jeringas de insulina', cantidad: 134, precioCompra: 168, distribuidor: null, precioVenta: 500 },
    { nombre: 'agujas 16 X 1/2', cantidad: 100, precioCompra: 130, distribuidor: null, precioVenta: 250 },
    { nombre: 'mangas palpar', cantidad: 36, precioCompra: 900, distribuidor: null, precioVenta: 2000 },
    { nombre: 'agujas 18 1/2', cantidad: 177, precioCompra: 150, distribuidor: null, precioVenta: 250 },
    { nombre: 'respirador industrial', cantidad: 1, precioCompra: 15825, distribuidor: 'agro paisa', precioVenta: 23000 },
    { nombre: 'agujas sutura recta', cantidad: 11, precioCompra: 1000, distribuidor: 'mil herrajes', precioVenta: 2500 },
    { nombre: 'agujas sutura curva', cantidad: 1, precioCompra: 1000, distribuidor: null, precioVenta: 1500 },
    { nombre: 'agujas super larga', cantidad: 1, precioCompra: 1200, distribuidor: 'mil herrajes', precioVenta: 1800 },
    { nombre: 'aguja recta pequeña', cantidad: 4, precioCompra: 1000, distribuidor: null, precioVenta: 1500 },
    { nombre: 'guantes quirurgicos x pares', cantidad: 100, precioCompra: 1000, distribuidor: null, precioVenta: 1500 },
    { nombre: 'tapabocas desechables', cantidad: 85, precioCompra: 250, distribuidor: null, precioVenta: 500 },
    { nombre: 'llaveros animales finos', cantidad: 7, precioCompra: 10000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'llaveros comunes', cantidad: 10, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'cuchillos solos', cantidad: 8, precioCompra: 2000, distribuidor: null, precioVenta: 2500 },
    { nombre: 'aguja desechable 18 larga', cantidad: 59, precioCompra: 75, distribuidor: 'unionagro', precioVenta: 250 },
    { nombre: 'babemic x 100ml', cantidad: 4, precioCompra: 7000, distribuidor: 'SAN ANT', precioVenta: 28000 },
    { nombre: 'babenil x 100ml', cantidad: 3, precioCompra: 8000, distribuidor: 'SAN ANT', precioVenta: 30000 },
    { nombre: 'bivermec equino x 100ml', cantidad: 8, precioCompra: 7000, distribuidor: 'SAN ANT', precioVenta: 20000 },
    { nombre: 'bivermec gold x 500ml', cantidad: 1, precioCompra: 18000, distribuidor: 'SAN ANT', precioVenta: 50000 },
    { nombre: 'dipirona x 100ml', cantidad: 3, precioCompra: 5000, distribuidor: 'SAN ANT', precioVenta: 15000 },
    { nombre: 'finadyne x 100ml', cantidad: 2, precioCompra: 22000, distribuidor: 'SAN ANT', precioVenta: 75000 },
    { nombre: 'finadyne x 10ml', cantidad: 4, precioCompra: 8080, distribuidor: 'SAN ANT', precioVenta: 20000 },
    { nombre: 'Forza pastilla flores X60', cantidad: 60, precioCompra: 5500, distribuidor: 'Agro Oriente', precioVenta: 250 },
    { nombre: 'Forza pastilla follage X60', cantidad: 41, precioCompra: 5500, distribuidor: 'agrooriente', precioVenta: 250 },
    { nombre: 'ganasal 5 mochila x 10 kg', cantidad: 2, precioCompra: 18796, distribuidor: 'INDAGRO', precioVenta: 23200 },
    { nombre: 'guantes plasticos amarillos', cantidad: 2, precioCompra: 1500, distribuidor: 'SAN ANT', precioVenta: 4500 },
    { nombre: 'kiver spray', cantidad: 1, precioCompra: 6880, distribuidor: 'SAN ANT', precioVenta: 9000 },
    { nombre: 'Oxitetraciclina servinsumos 10 ml', cantidad: 9, precioCompra: 2800, distribuidor: 'unionagro', precioVenta: 3500 },
    { nombre: 'premezcla x 5 kilos', cantidad: 1, precioCompra: 13781, distribuidor: 'INDAGRO', precioVenta: 20000 },
    { nombre: 'trypamidium sobre', cantidad: 6, precioCompra: 20000, distribuidor: 'SAN ANT', precioVenta: 30000 },
    { nombre: 'agujas 18 cortas', cantidad: 44, precioCompra: 128, distribuidor: null, precioVenta: 250 },
    { nombre: 'agujas 21', cantidad: 70, precioCompra: 128, distribuidor: null, precioVenta: 250 },
    { nombre: 'anapox 500 ml', cantidad: 1, precioCompra: 9905, distribuidor: 'san antonio', precioVenta: 35000 },
    { nombre: 'emicina 100 ml', cantidad: 3, precioCompra: 13448, distribuidor: 'san antonio', precioVenta: 28000 },
    { nombre: 'ivendex 3.15 magnum 500 ml', cantidad: 1, precioCompra: 21000, distribuidor: 'san antonio', precioVenta: 55000 },
    { nombre: 'jeringa desechable 5 ml', cantidad: 17, precioCompra: 350, distribuidor: 'san antonio', precioVenta: 500 },
    { nombre: 'marverrapido', cantidad: 4, precioCompra: 8500, distribuidor: 'unionagro', precioVenta: 8500 },
    { nombre: 'metricure jeringa', cantidad: 5, precioCompra: 9000, distribuidor: 'san antonio', precioVenta: 20000 },
    { nombre: 'pasta descornadora', cantidad: 1, precioCompra: 12712, distribuidor: 'san antonio', precioVenta: 25000 },
    { nombre: 'pomasana 200 grs', cantidad: 2, precioCompra: 5120, distribuidor: 'san antonio', precioVenta: 10000 },
    { nombre: 'yodocan 100 ml', cantidad: 1, precioCompra: 4000, distribuidor: 'san antonio', precioVenta: 15000 },
    { nombre: 'albendex 200 ml', cantidad: 5, precioCompra: 8045, distribuidor: 'san', precioVenta: 15000 },
    { nombre: 'combibac R8 50 DS', cantidad: 1, precioCompra: 29000, distribuidor: 'unionagro', precioVenta: 40500 },
    { nombre: 'Floxil inyectable 100 ml', cantidad: 1, precioCompra: 7000, distribuidor: 'san antonio', precioVenta: 25000 },
    { nombre: 'Machetes', cantidad: 1, precioCompra: 8000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'oxitetraciclina vicar 100 ml', cantidad: 4, precioCompra: 8800, distribuidor: 'alianza', precioVenta: 11000 },
    { nombre: 'seda quirurgica negra', cantidad: 1, precioCompra: 6000, distribuidor: 'vetiagro', precioVenta: 7500 },
    { nombre: 'vetalgina 100 ml', cantidad: 4, precioCompra: 15000, distribuidor: 'san antonio', precioVenta: 25000 },
    { nombre: 'Dexapal 100 ml', cantidad: 7, precioCompra: 7200, distribuidor: 'san antonio', precioVenta: 28000 },
    { nombre: 'Jeringas de insulina agro oriente', cantidad: 163, precioCompra: 180, distribuidor: 'agro oriente', precioVenta: 350 },
    { nombre: 'Fumigadora Handy 10 litros', cantidad: 1, precioCompra: 69999, distribuidor: 'superagro', precioVenta: 88000 },
    { nombre: 'union 3/4', cantidad: 2, precioCompra: 700, distribuidor: 'uniferragro', precioVenta: 900 },
    { nombre: 'union 1', cantidad: 6, precioCompra: 900, distribuidor: 'uniferragro', precioVenta: 1200 },
    { nombre: 'codo politleno 1/2', cantidad: 4, precioCompra: 420, distribuidor: 'uniferragro', precioVenta: 700 },
    { nombre: 'codo politleno 3/4', cantidad: 6, precioCompra: 588, distribuidor: 'uniferragro', precioVenta: 800 },
    { nombre: 'codo polotileno 1', cantidad: 5, precioCompra: 756, distribuidor: 'uniferragro', precioVenta: 1000 },
    { nombre: 'Acople macho 1/2', cantidad: 3, precioCompra: 600, distribuidor: 'uniferragro', precioVenta: 800 },
    { nombre: 'puntilla de acero 2.5 X 1/2', cantidad: 9, precioCompra: 4580, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntilla de acero 2 X 12', cantidad: 1, precioCompra: 4580, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntilla acero 3x9', cantidad: 13, precioCompra: 4580, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntilla acero 1/4 X 9', cantidad: 10, precioCompra: 2800, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntilla 2 X 12', cantidad: 6, precioCompra: 4397, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntillas 2/1 x 11', cantidad: 13, precioCompra: 4397, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntillas 3 X 9', cantidad: 13, precioCompra: 4397, distribuidor: 'indurruedas', precioVenta: 7000 },
    { nombre: 'puntillas 5 X 5', cantidad: 12, precioCompra: 9942, distribuidor: 'indurruedas', precioVenta: 12000 },
    { nombre: 'tapabocas industrial', cantidad: 16, precioCompra: 350, distribuidor: 'quimicos', precioVenta: 1000 },
    { nombre: 'lazos de fibra delgados', cantidad: 33, precioCompra: 1000, distribuidor: null, precioVenta: 3800 },
    { nombre: 'repirox litro', cantidad: 1, precioCompra: 10000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'tiza china', cantidad: 17, precioCompra: 300, distribuidor: 'paisas', precioVenta: 1000 },
    { nombre: 'semilla zanahoria', cantidad: 7, precioCompra: 2700, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'semilla perejil', cantidad: 3, precioCompra: 2700, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'semilla pimenton', cantidad: 4, precioCompra: 2700, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'cilantro reempacado', cantidad: 16, precioCompra: 2700, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'pipino', cantidad: 14, precioCompra: 2700, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'semilla de tomate', cantidad: 22, precioCompra: 3000, distribuidor: null, precioVenta: 4000 },
    { nombre: 'semilla acelga', cantidad: 1, precioCompra: 2700, distribuidor: null, precioVenta: 4000 },
    { nombre: 'semilla espinaca', cantidad: 5, precioCompra: 2000, distribuidor: null, precioVenta: 4000 },
    { nombre: 'semilla cebolla larga', cantidad: 4, precioCompra: 2000, distribuidor: null, precioVenta: 4000 },
    { nombre: 'semilla pimenton vetiagro', cantidad: 4, precioCompra: 1500, distribuidor: 'vetiagro', precioVenta: 4000 },
    { nombre: 'Mastridy secado X 10 ml', cantidad: 4, precioCompra: 6476, distribuidor: 'UNIONAGRO', precioVenta: 8500 },
    { nombre: 'tapabocas tela grandes', cantidad: 3, precioCompra: 1000, distribuidor: null, precioVenta: 2000 },
    { nombre: 'Brachiaria marandu', cantidad: 4, precioCompra: 25924, distribuidor: 'AGROPAISA', precioVenta: 35000 },
    { nombre: 'cuchillas de bisturi', cantidad: 75, precioCompra: 252, distribuidor: 'UNIONAGRO', precioVenta: 800 },
    { nombre: 'fibra tomatera', cantidad: 5, precioCompra: 10789, distribuidor: 'UNIFERRAGRO', precioVenta: 16000 },
    { nombre: 'creolina 60 ml', cantidad: 5, precioCompra: 3000, distribuidor: null, precioVenta: 5000 },
    { nombre: 'creolina 400', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'cuerda matizada #8 X 300 mts', cantidad: 100, precioCompra: 946, distribuidor: 'INDURRUEDAS', precioVenta: 1500 },
    { nombre: 'stormogyl pastillas', cantidad: 12, precioCompra: 1800, distribuidor: null, precioVenta: 2500 },
    { nombre: 'freno barril acero', cantidad: 2, precioCompra: 55000, distribuidor: 'sogamoso', precioVenta: 65000 },
    { nombre: 'freno corriente', cantidad: 5, precioCompra: 36000, distribuidor: 'sogamoso', precioVenta: 55000 },
    { nombre: 'sinchon Naylon', cantidad: 7, precioCompra: 20000, distribuidor: 'sogamoso', precioVenta: 25000 },
    { nombre: 'riendas doble riata', cantidad: 1, precioCompra: 22000, distribuidor: 'sogamoso', precioVenta: 32000 },
    { nombre: 'riendas gruesas corrientes', cantidad: 1, precioCompra: 26000, distribuidor: 'sogamoso', precioVenta: 37000 },
    { nombre: 'Metrivet ovulos caja', cantidad: 12, precioCompra: 3250, distribuidor: 'UNIONAGRO', precioVenta: 5000 },
    { nombre: 'semilla maiz', cantidad: 3, precioCompra: 15000, distribuidor: 'EL TORO', precioVenta: 15000 },
    { nombre: 'ponchos sencillos surtidos', cantidad: 12, precioCompra: 7000, distribuidor: null, precioVenta: 16000 },
    { nombre: 'gorra niños', cantidad: 15, precioCompra: 4000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Gorras sencillas', cantidad: 13, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'Gorras finas', cantidad: 17, precioCompra: 28000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'funda y macheta chaparraluna', cantidad: 6, precioCompra: 38000, distribuidor: null, precioVenta: 50000 },
    { nombre: 'macheta y funda rabo de gallo ancha', cantidad: 12, precioCompra: 45000, distribuidor: null, precioVenta: 62000 },
    { nombre: 'fundas chaparraluna', cantidad: 6, precioCompra: 15000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'cuerda matizada #10 X 250 mts', cantidad: 200, precioCompra: 1448, distribuidor: null, precioVenta: 2000 },
    { nombre: 'ponchos finos', cantidad: 6, precioCompra: 25000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'lima bellota', cantidad: 3, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'cordon laura #3 X 200 mts', cantidad: 200, precioCompra: 600, distribuidor: null, precioVenta: 800 },
    { nombre: 'cordon laura #4 X 200 mts', cantidad: 200, precioCompra: 650, distribuidor: null, precioVenta: 1000 },
    { nombre: 'collar isabelino XS', cantidad: 6, precioCompra: 6000, distribuidor: 'Agrocampo', precioVenta: 8500 },
    { nombre: 'collar isabelino M', cantidad: 3, precioCompra: 12154, distribuidor: 'Agrocampo', precioVenta: 15000 },
    { nombre: 'patas de pollo carnaza', cantidad: 22, precioCompra: 800, distribuidor: null, precioVenta: 1500 },
    { nombre: 'galletas perros kilo x 100 unidades', cantidad: 2, precioCompra: 200, distribuidor: null, precioVenta: 500 },
    { nombre: 'collar pincher', cantidad: 4, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'collar riata mediano sencillo', cantidad: 3, precioCompra: 3000, distribuidor: null, precioVenta: 5000 },
    { nombre: 'chaleco perros', cantidad: 1, precioCompra: 30000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'collares riata medianos pierna', cantidad: 4, precioCompra: 6000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'collar pechera riata grande', cantidad: 5, precioCompra: 7000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'cuello riata pequeños', cantidad: 4, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'estuche celular cuero grande', cantidad: 3, precioCompra: 18000, distribuidor: null, precioVenta: 25000 },
    { nombre: 'sillas de lujo', cantidad: 2, precioCompra: 13000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'llaveros de navajas', cantidad: 4, precioCompra: 1500, distribuidor: null, precioVenta: 2000 },
    { nombre: 'navaja pistola', cantidad: 2, precioCompra: 20000, distribuidor: null, precioVenta: 25000 },
    { nombre: 'triple 15 x kilos', cantidad: 17, precioCompra: 3366, distribuidor: null, precioVenta: 5000 },
    { nombre: 'bosales perros tela negros', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'navaja tarjeta multiusos', cantidad: 2, precioCompra: 2500, distribuidor: null, precioVenta: 5000 },
    { nombre: 'aisladores trava 100 X unidades', cantidad: 9, precioCompra: 17000, distribuidor: null, precioVenta: 22000 },
    { nombre: 'aislador de pera x 100 unidades', cantidad: 6, precioCompra: 18000, distribuidor: null, precioVenta: 25000 },
    { nombre: 'manguetas portillo', cantidad: 4, precioCompra: 4000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'kit portillo 3 mts', cantidad: 2, precioCompra: 11000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'kit portillo 5 mts', cantidad: 2, precioCompra: 12200, distribuidor: null, precioVenta: 20000 },
    { nombre: 'tensor pequeño', cantidad: 6, precioCompra: 3300, distribuidor: null, precioVenta: 5000 },
    { nombre: 'vacuna rabia perros', cantidad: 7, precioCompra: 10000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'herraduras', cantidad: 14, precioCompra: 4500, distribuidor: 'talabarteria', precioVenta: 7500 },
    { nombre: 'fumigadora galon 4 litros', cantidad: 4, precioCompra: 44000, distribuidor: 'superagro', precioVenta: 78000 },
    { nombre: 'fumigadora aliada royal x 20 litros', cantidad: 1, precioCompra: 288000, distribuidor: 'superagro', precioVenta: 280000 },
    { nombre: 'fumigadora trombon 10 litros', cantidad: 2, precioCompra: 165000, distribuidor: 'superagro', precioVenta: 170000 },
    { nombre: 'linterna mediana recargable con estuche', cantidad: 5, precioCompra: 17500, distribuidor: null, precioVenta: 25000 },
    { nombre: 'linterna pequeña recargable con estuche', cantidad: 1, precioCompra: 8500, distribuidor: null, precioVenta: 14000 },
    { nombre: 'Forros lona', cantidad: 2, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Shampu perros', cantidad: 1, precioCompra: 9000, distribuidor: null, precioVenta: 14000 },
    { nombre: 'baños secos spray', cantidad: 5, precioCompra: 8500, distribuidor: null, precioVenta: 9500 },
    { nombre: 'ganabol x 10 cm', cantidad: 3, precioCompra: 13500, distribuidor: null, precioVenta: 15500 },
    { nombre: 'malla gallinero metalica 36 mts X 1.50 mts', cantidad: 1, precioCompra: 96000, distribuidor: null, precioVenta: 100000 },
    { nombre: 'kavitex 20/20', cantidad: 11, precioCompra: 17900, distribuidor: null, precioVenta: 25000 },
    { nombre: 'cuchilla bellota roja', cantidad: 3, precioCompra: 8900, distribuidor: null, precioVenta: 13000 },
    { nombre: 'aceite mineral litro', cantidad: 1, precioCompra: 13000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'sulfato Mg libra', cantidad: 12, precioCompra: 1560, distribuidor: null, precioVenta: 4000 },
    { nombre: 'pretal catabra fino', cantidad: 7, precioCompra: 8000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'pretales corriente', cantidad: 28, precioCompra: 4000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'porcifer hierro 10 ml', cantidad: 7, precioCompra: 6800, distribuidor: null, precioVenta: 10000 },
    { nombre: 'quinocal 25 grs pastillas', cantidad: 120, precioCompra: 483, distribuidor: null, precioVenta: 700 },
    { nombre: 'candados pequeños', cantidad: 16, precioCompra: 2000, distribuidor: null, precioVenta: 3500 },
    { nombre: 'candados grandes', cantidad: 4, precioCompra: 8000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'Todo en uno kilo', cantidad: 7, precioCompra: 11510, distribuidor: null, precioVenta: 17500 },
    { nombre: 'linterna comun pequeña', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 14000 },
    { nombre: 'linterna comun mediana', cantidad: 2, precioCompra: 6000, distribuidor: null, precioVenta: 8500 },
    { nombre: 'linterna comun grande', cantidad: 4, precioCompra: 11000, distribuidor: null, precioVenta: 16000 },
    { nombre: 'macheta funda rabo de gallo', cantidad: 11, precioCompra: 42000, distribuidor: null, precioVenta: 50000 },
    { nombre: 'cuchillo con funda pequeña', cantidad: 2, precioCompra: 27000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'metoclopramida capsulas', cantidad: 10, precioCompra: 163, distribuidor: null, precioVenta: 500 },
    { nombre: 'seda quirurgica', cantidad: 3, precioCompra: 6000, distribuidor: null, precioVenta: 8000 },
    { nombre: 'gota magica', cantidad: 17, precioCompra: 600, distribuidor: null, precioVenta: 1000 },
    { nombre: 'palas jardineria', cantidad: 1, precioCompra: 5000, distribuidor: null, precioVenta: 8000 },
    { nombre: 'argollas lazo', cantidad: 21, precioCompra: 2000, distribuidor: null, precioVenta: 3000 },
    { nombre: 'agujas roma', cantidad: 5, precioCompra: 200, distribuidor: null, precioVenta: 1000 },
    { nombre: 'macroespiran X 13 U.I', cantidad: 3, precioCompra: 19500, distribuidor: null, precioVenta: 30000 },
    { nombre: 'cinta trasparente', cantidad: 12, precioCompra: 250, distribuidor: null, precioVenta: 500 },
    { nombre: 'clavos de herrar cajas', cantidad: 3, precioCompra: 15000, distribuidor: null, precioVenta: 22000 },
    { nombre: 'alambre galvanizado #18 X kilo', cantidad: 3, precioCompra: 10782, distribuidor: null, precioVenta: 14000 },
    { nombre: 'azufre x libra', cantidad: 15, precioCompra: 2600, distribuidor: 'quimicos', precioVenta: 4000 },
    { nombre: 'Roflaxivem X 50 ml', cantidad: 1, precioCompra: 22666, distribuidor: null, precioVenta: 32000 },
    { nombre: 'levamisol 20 ml', cantidad: 1, precioCompra: 10100, distribuidor: null, precioVenta: 14500 },
    { nombre: 'levamisol 100 ml', cantidad: 2, precioCompra: 23000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'levamisol 50 ml', cantidad: 6, precioCompra: 12320, distribuidor: null, precioVenta: 17500 },
    { nombre: 'Trimediazina 100 ml', cantidad: 2, precioCompra: 44100, distribuidor: null, precioVenta: 48500 },
    { nombre: 'bota macha', cantidad: 3, precioCompra: 25519, distribuidor: null, precioVenta: 40000 },
    { nombre: 'bota ranger', cantidad: 3, precioCompra: 18300, distribuidor: null, precioVenta: 38000 },
    { nombre: 'equipo macrogoteo', cantidad: 14, precioCompra: 1600, distribuidor: null, precioVenta: 3500 },
    { nombre: 'mamiland 60 gr', cantidad: 2, precioCompra: 11000, distribuidor: null, precioVenta: 15500 },
    { nombre: 'mamiland 100 grs', cantidad: 2, precioCompra: 18000, distribuidor: null, precioVenta: 22500 },
    { nombre: 'Masticilin jeringa antimastitica', cantidad: 2, precioCompra: 6500, distribuidor: null, precioVenta: 9500 },
    { nombre: 'lincocelin secado jeringas', cantidad: 3, precioCompra: 7100, distribuidor: null, precioVenta: 9500 },
    { nombre: 'pegante ratones', cantidad: 10, precioCompra: 4000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'cinta moscas', cantidad: 4, precioCompra: 500, distribuidor: null, precioVenta: 1500 },
    { nombre: 'pomada verde', cantidad: 4, precioCompra: 30000, distribuidor: null, precioVenta: 45000 },
    { nombre: 'Doxicam tabletas', cantidad: 16, precioCompra: 1050, distribuidor: null, precioVenta: 2000 },
    { nombre: 'panzer sobre', cantidad: 14, precioCompra: 3900, distribuidor: null, precioVenta: 7500 },
    { nombre: 'cadenas perros delgadas', cantidad: 8, precioCompra: 4000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'aceite mineral', cantidad: 4, precioCompra: 6500, distribuidor: null, precioVenta: 10000 },
    { nombre: 'destetador pequeño', cantidad: 36, precioCompra: 2800, distribuidor: null, precioVenta: 4000 },
    { nombre: 'denty pets', cantidad: 3, precioCompra: 8500, distribuidor: null, precioVenta: 12000 },
    { nombre: 'locion perros', cantidad: 1, precioCompra: 10000, distribuidor: null, precioVenta: 14000 },
    { nombre: 'bota estampada', cantidad: 6, precioCompra: 40967, distribuidor: null, precioVenta: 48000 },
    { nombre: 'bota andina niños', cantidad: 31, precioCompra: 21029, distribuidor: null, precioVenta: 27000 },
    { nombre: 'ubrevet 30 grs', cantidad: 7, precioCompra: 24670, distribuidor: null, precioVenta: 28000 },
    { nombre: 'zondas mamarias', cantidad: 10, precioCompra: 7800, distribuidor: null, precioVenta: 12000 },
    { nombre: 'destetador grande', cantidad: 7, precioCompra: 2400, distribuidor: null, precioVenta: 5000 },
    { nombre: 'tronador litro', cantidad: 3, precioCompra: 24500, distribuidor: null, precioVenta: 32000 },
    { nombre: 'Alambre negro kilo', cantidad: 8, precioCompra: 6615, distribuidor: null, precioVenta: 10000 },
    { nombre: 'catabras', cantidad: 8, precioCompra: 10000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'grasa', cantidad: 6, precioCompra: 7200, distribuidor: null, precioVenta: 7500 },
    { nombre: 'Aceite 2 tiempos super moto', cantidad: 9, precioCompra: 12916, distribuidor: null, precioVenta: 18000 },
    { nombre: 'Aceite verde', cantidad: 5, precioCompra: 6916, distribuidor: null, precioVenta: 12000 },
    { nombre: 'jabon asuntol x 100 gr', cantidad: 11, precioCompra: 10044, distribuidor: null, precioVenta: 13000 },
    { nombre: 'jabon pulvican', cantidad: 4, precioCompra: 8400, distribuidor: null, precioVenta: 12000 },
    { nombre: 'complejo B X 50 ml', cantidad: 7, precioCompra: 14000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'complejo B X 100 ml', cantidad: 9, precioCompra: 19500, distribuidor: null, precioVenta: 22000 },
    { nombre: 'biomectrina X 120 ml', cantidad: 5, precioCompra: 12200, distribuidor: null, precioVenta: 18000 },
    { nombre: 'bombas fumigar pequeñas corriente', cantidad: 1, precioCompra: 8000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'bombas fumigar medianas corriente', cantidad: 3, precioCompra: 10000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'complejo B X 250 ml', cantidad: 3, precioCompra: 41900, distribuidor: null, precioVenta: 60000 },
    { nombre: 'trevesec 30 ml', cantidad: 2, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'zinpar tabletas (ivermectina)', cantidad: 19, precioCompra: 1380, distribuidor: null, precioVenta: 2500 },
    { nombre: 'fosfoland 20 ml', cantidad: 1, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'botas venus andina', cantidad: 31, precioCompra: 27511, distribuidor: null, precioVenta: 39000 },
    { nombre: 'botas venus llanera', cantidad: 43, precioCompra: 42341, distribuidor: null, precioVenta: 55000 },
    { nombre: 'merthiolitos', cantidad: 8, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'vermicerdo sobre', cantidad: 9, precioCompra: 3300, distribuidor: null, precioVenta: 5000 },
    { nombre: 'cuchillos finos', cantidad: 2, precioCompra: 30000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'apero de cabeza sencillo', cantidad: 3, precioCompra: 45000, distribuidor: null, precioVenta: 60000 },
    { nombre: 'fundas rabo gallo', cantidad: 10, precioCompra: 23000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'Arritrancos', cantidad: 1, precioCompra: 28000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'baticolas', cantidad: 6, precioCompra: 23000, distribuidor: null, precioVenta: 26000 },
    { nombre: 'sacos', cantidad: 14, precioCompra: 1000, distribuidor: null, precioVenta: 2800 },
    { nombre: 'ivermen dorado 3.15% X 50 ml', cantidad: 6, precioCompra: 16882, distribuidor: null, precioVenta: 25000 },
    { nombre: 'trimedizina X 10 ml', cantidad: 13, precioCompra: 11571, distribuidor: null, precioVenta: 15000 },
    { nombre: 'icornol pasta', cantidad: 2, precioCompra: 17140, distribuidor: null, precioVenta: 25000 },
    { nombre: 'chupos', cantidad: 15, precioCompra: 1983, distribuidor: null, precioVenta: 4000 },
    { nombre: 'cartuchera celular cuero tejido', cantidad: 3, precioCompra: 30000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'estuche navaja cuero mediano', cantidad: 8, precioCompra: 18000, distribuidor: null, precioVenta: 23000 },
    { nombre: 'estuche navaja cuero pequeño', cantidad: 1, precioCompra: 16000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'llaveros metro', cantidad: 2, precioCompra: 1200, distribuidor: null, precioVenta: 2500 },
    { nombre: 'ganabol 50 ml', cantidad: 8, precioCompra: 34800, distribuidor: null, precioVenta: 45000 },
    { nombre: 'trevesec 50 ml', cantidad: 6, precioCompra: 31400, distribuidor: null, precioVenta: 42000 },
    { nombre: 'shampu clorexidina', cantidad: 2, precioCompra: 26000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'sales de hidratacion oral', cantidad: 22, precioCompra: 2500, distribuidor: null, precioVenta: 4000 },
    { nombre: 'dexametasona ampolla', cantidad: 5, precioCompra: 2800, distribuidor: null, precioVenta: 4500 },
    { nombre: 'teflon 1/2', cantidad: 7, precioCompra: 500, distribuidor: null, precioVenta: 1000 },
    { nombre: 'teflon 3/4', cantidad: 12, precioCompra: 1000, distribuidor: null, precioVenta: 1500 },
    { nombre: 'sombreros pintados', cantidad: 2, precioCompra: 35000, distribuidor: null, precioVenta: 50000 },
    { nombre: 'biometrina 100 ml', cantidad: 5, precioCompra: 23000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'yodo 60 ml', cantidad: 12, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'yodo 120 ml', cantidad: 5, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'manguera 1/2 x 200 mts delgada', cantidad: 1, precioCompra: 50000, distribuidor: null, precioVenta: 60000 },
    { nombre: 'manguera 1/2 x 200 mts gruesa', cantidad: 1, precioCompra: 70000, distribuidor: null, precioVenta: 80000 },
    { nombre: 'melaza pimpina', cantidad: 1, precioCompra: 45000, distribuidor: null, precioVenta: 50000 },
    { nombre: 'tripa de pollo x bolas', cantidad: 2, precioCompra: 5000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'chacras medianas', cantidad: 6, precioCompra: 20000, distribuidor: null, precioVenta: 25000 },
    { nombre: 'chacras grandes', cantidad: 1, precioCompra: 25000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'vacuna neumodiar', cantidad: 27, precioCompra: 4760, distribuidor: null, precioVenta: 7500 },
    { nombre: 'prednizoo 20 MG tabletas', cantidad: 36, precioCompra: 900, distribuidor: null, precioVenta: 1800 },
    { nombre: 'Algicam 4Mg X 10 tabletas perros', cantidad: 10, precioCompra: 2400, distribuidor: null, precioVenta: 3500 },
    { nombre: 'Diciclin 200 tableta', cantidad: 16, precioCompra: 1000, distribuidor: null, precioVenta: 2500 },
    { nombre: 'Diciclin 100 tableta', cantidad: 30, precioCompra: 1200, distribuidor: null, precioVenta: 2000 },
    { nombre: 'zimpar tabletas', cantidad: 19, precioCompra: 1360, distribuidor: null, precioVenta: 2000 },
    { nombre: 'Derrivon X 250 ml', cantidad: 1, precioCompra: 33000, distribuidor: null, precioVenta: 43000 },
    { nombre: 'Nexabest ungüento X 200 grs', cantidad: 2, precioCompra: 26000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'Arciones', cantidad: 4, precioCompra: 15000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'fumigadora Activa', cantidad: 2, precioCompra: 232200, distribuidor: null, precioVenta: 295000 },
    { nombre: 'purga canipets 2 ml', cantidad: 11, precioCompra: 4200, distribuidor: null, precioVenta: 5000 },
    { nombre: 'purga jeringa perros CANIPETS X 5 ml', cantidad: 6, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'ultrachoiche X 10 DS', cantidad: 8, precioCompra: 15000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'azul metileno sobre', cantidad: 28, precioCompra: 6400, distribuidor: null, precioVenta: 7500 },
    { nombre: 'funda socorrana solas', cantidad: 9, precioCompra: 22000, distribuidor: null, precioVenta: 27000 },
    { nombre: 'macheta solas', cantidad: 13, precioCompra: 18000, distribuidor: null, precioVenta: 22000 },
    { nombre: 'premezcla mineral GanafoX kilos', cantidad: 33, precioCompra: 9200, distribuidor: null, precioVenta: 12000 },
    { nombre: 'italcan X 30 kilos', cantidad: 26, precioCompra: 3666, distribuidor: null, precioVenta: 5000 },
    { nombre: 'lazo matizado 8 mm X mts', cantidad: 300, precioCompra: 963, distribuidor: null, precioVenta: 1500 },
    { nombre: 'destetadores pequeños', cantidad: 36, precioCompra: 1500, distribuidor: null, precioVenta: 4000 },
    { nombre: 'trevesec 30 ml repuesto', cantidad: 2, precioCompra: 19000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'sobres pedegree', cantidad: 36, precioCompra: 2537, distribuidor: null, precioVenta: 3000 },
    { nombre: 'shampu cojin antipulgas', cantidad: 7, precioCompra: 3898, distribuidor: null, precioVenta: 6000 },
    { nombre: 'raid antipulgas', cantidad: 4, precioCompra: 16953, distribuidor: null, precioVenta: 19000 },
    { nombre: 'raid azul', cantidad: 9, precioCompra: 16415, distribuidor: null, precioVenta: 18500 },
    { nombre: 'chunky adulto x 500 grs', cantidad: 9, precioCompra: 3504, distribuidor: null, precioVenta: 4800 },
    { nombre: 'chunky cachorro x 500 grs', cantidad: 10, precioCompra: 4537, distribuidor: null, precioVenta: 5000 },
    { nombre: 'Delidog pote comida mojada', cantidad: 7, precioCompra: 3982, distribuidor: null, precioVenta: 5000 },
    { nombre: 'Menu natural surtido salchichon', cantidad: 2, precioCompra: 6000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Menu natural cremoso', cantidad: 54, precioCompra: 1645, distribuidor: null, precioVenta: 2000 },
    { nombre: 'bombonera Nutri bar chocolatina', cantidad: 18, precioCompra: 2356, distribuidor: null, precioVenta: 2500 },
    { nombre: 'Potenzol 3000 Lt', cantidad: 1, precioCompra: 31800, distribuidor: null, precioVenta: 35000 },
    { nombre: 'cuelleros grandes', cantidad: 3, precioCompra: 6000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'oxitetraciclina Mk 50 X 50 ML', cantidad: 9, precioCompra: 10100, distribuidor: null, precioVenta: 14500 },
    { nombre: 'Oxitetraciclina Mk 200 X 50 ML', cantidad: 10, precioCompra: 21700, distribuidor: null, precioVenta: 28500 },
    { nombre: 'Dexapen 10 ml', cantidad: 4, precioCompra: 18200, distribuidor: null, precioVenta: 24000 },
    { nombre: 'trampa corriente grande', cantidad: 11, precioCompra: 3500, distribuidor: null, precioVenta: 6000 },
    { nombre: 'trampa madera grande', cantidad: 7, precioCompra: 8000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'fulminado 20 ml', cantidad: 17, precioCompra: 7800, distribuidor: null, precioVenta: 10500 },
    { nombre: 'aguja metalicas', cantidad: 85, precioCompra: 1300, distribuidor: null, precioVenta: 2000 },
    { nombre: 'collares perro grandes', cantidad: 3, precioCompra: 9000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'Aguja metalicas repuesto', cantidad: 36, precioCompra: 1092, distribuidor: null, precioVenta: 2000 },
    { nombre: 'iverhose jeringa', cantidad: 8, precioCompra: 17500, distribuidor: null, precioVenta: 25000 },
    { nombre: 'garrabaño X 33 ml', cantidad: 6, precioCompra: 11300, distribuidor: null, precioVenta: 13500 },
    { nombre: 'paravet sobre X 15 grs', cantidad: 62, precioCompra: 3200, distribuidor: null, precioVenta: 5500 },
    { nombre: 'jeringa plastica X 20 ml', cantidad: 2, precioCompra: 30252, distribuidor: null, precioVenta: 40000 },
    { nombre: 'hilo atafacil', cantidad: 11, precioCompra: 3500, distribuidor: null, precioVenta: 4500 },
    { nombre: 'hormitox hormigas', cantidad: 9, precioCompra: 13000, distribuidor: null, precioVenta: 17000 },
    { nombre: 'catabras repuesto', cantidad: 7, precioCompra: 10500, distribuidor: null, precioVenta: 14000 },
    { nombre: 'rollos de licra pequeña', cantidad: 8, precioCompra: 1000, distribuidor: null, precioVenta: 2000 },
    { nombre: 'fundas rabo de gallo', cantidad: 12, precioCompra: 27000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'sicario liquido', cantidad: 13, precioCompra: 2500, distribuidor: null, precioVenta: 4000 },
    { nombre: 'guantes azul corriente tela', cantidad: 12, precioCompra: 2500, distribuidor: null, precioVenta: 4000 },
    { nombre: 'bolsa neftalina', cantidad: 9, precioCompra: 2800, distribuidor: null, precioVenta: 5000 },
    { nombre: 'jabon antipulgas cannamor', cantidad: 2, precioCompra: 11858, distribuidor: null, precioVenta: 13000 },
    { nombre: 'sal blanca 40 kg', cantidad: 11, precioCompra: 15500, distribuidor: null, precioVenta: 28000 },
    { nombre: 'sal blanca 50 kg', cantidad: 3, precioCompra: 18000, distribuidor: null, precioVenta: 31000 },
    { nombre: 'sal pigmentada X 50 kg', cantidad: 3, precioCompra: 18000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'sal pigmentada roja x kilos', cantidad: 9, precioCompra: 2700, distribuidor: null, precioVenta: 4500 },
    { nombre: 'sal 30 kilos', cantidad: 10, precioCompra: 12000, distribuidor: null, precioVenta: 23000 },
    { nombre: 'Vacuna parvovirosis', cantidad: 30, precioCompra: 11000, distribuidor: null, precioVenta: 15500 },
    { nombre: 'vacuna triple', cantidad: 14, precioCompra: 15500, distribuidor: null, precioVenta: 25000 },
    { nombre: 'vacuna quintuple', cantidad: 8, precioCompra: 22500, distribuidor: null, precioVenta: 30000 },
    { nombre: 'Tripen 9 U.I', cantidad: 2, precioCompra: 38000, distribuidor: null, precioVenta: 42000 },
    { nombre: 'Triplen 6 U.I', cantidad: 2, precioCompra: 29000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'tabla de raton verde', cantidad: 6, precioCompra: 2500, distribuidor: null, precioVenta: 4000 },
    { nombre: 'tabla raton amarilla', cantidad: 8, precioCompra: 3500, distribuidor: null, precioVenta: 5500 },
    { nombre: 'gel cucarachas', cantidad: 9, precioCompra: 4500, distribuidor: null, precioVenta: 7000 },
    { nombre: 'iventrina X 250 ml', cantidad: 15, precioCompra: 13100, distribuidor: null, precioVenta: 17000 },
    { nombre: 'Grapa larga', cantidad: 19, precioCompra: 11281, distribuidor: null, precioVenta: 13000 },
    { nombre: 'piperazina pastilla sobre', cantidad: 144, precioCompra: 1083, distribuidor: null, precioVenta: 1500 },
    { nombre: 'ankofen pastillas', cantidad: 20, precioCompra: 1900, distribuidor: null, precioVenta: 2500 },
    { nombre: 'anpromax sobre', cantidad: 24, precioCompra: 9800, distribuidor: null, precioVenta: 13000 },
    { nombre: 'navajas surtidas', cantidad: 10, precioCompra: 9500, distribuidor: null, precioVenta: 13000 },
    { nombre: 'italcan perros X kilos', cantidad: 30, precioCompra: 3666, distribuidor: null, precioVenta: 4500 },
    { nombre: 'lactato de ringer 1000 ml', cantidad: 3, precioCompra: 5900, distribuidor: null, precioVenta: 8000 },
    { nombre: 'cloruro de sodio 1000 ml', cantidad: 6, precioCompra: 5200, distribuidor: null, precioVenta: 7500 },
    { nombre: 'cloruro de sodio y lactato 500 ml', cantidad: 2, precioCompra: 3900, distribuidor: null, precioVenta: 5000 },
    { nombre: 'patacabra navaja', cantidad: 11, precioCompra: 2000, distribuidor: null, precioVenta: 3000 },
    { nombre: 'cipertop x 375 ml', cantidad: 6, precioCompra: 23100, distribuidor: null, precioVenta: 30000 },
    { nombre: 'navajas capar', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'romade cojin', cantidad: 146, precioCompra: 1900, distribuidor: null, precioVenta: 3500 },
    { nombre: 'calsyn oral', cantidad: 50, precioCompra: 5600, distribuidor: null, precioVenta: 7800 },
    { nombre: 'Eivem 200 X 250 ml', cantidad: 3, precioCompra: 77800, distribuidor: null, precioVenta: 85000 },
    { nombre: 'Meloxivem oral X 10 ml', cantidad: 8, precioCompra: 7000, distribuidor: null, precioVenta: 7500 },
    { nombre: 'Emivem 200 X 100', cantidad: 2, precioCompra: 35600, distribuidor: null, precioVenta: 44000 },
    { nombre: 'Purgacan perros 5 cm', cantidad: 9, precioCompra: 6400, distribuidor: null, precioVenta: 8000 },
    { nombre: 'Metsulfuron 100 grs', cantidad: 5, precioCompra: 12544, distribuidor: null, precioVenta: 16000 },
    { nombre: 'Parnerth 110 grs', cantidad: 5, precioCompra: 15500, distribuidor: null, precioVenta: 18000 },
    { nombre: 'Partner 22 grs', cantidad: 10, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Emboscada x 15 grs', cantidad: 4, precioCompra: 4000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'sobre pedegre', cantidad: 38, precioCompra: 2385, distribuidor: null, precioVenta: 3000 },
    { nombre: 'arena gatos', cantidad: 3, precioCompra: 15200, distribuidor: null, precioVenta: 17000 },
    { nombre: 'cojin shampu can amor', cantidad: 14, precioCompra: 3183, distribuidor: null, precioVenta: 5000 },
    { nombre: 'Alambre puas 12.5 X 400 mts vaquero', cantidad: 1, precioCompra: 362000, distribuidor: null, precioVenta: 398000 },
    { nombre: 'Alambre puas 14.5 X 350 mts', cantidad: 1, precioCompra: 228500, distribuidor: null, precioVenta: 298000 },
    { nombre: 'Alambre puas 14.5 X 500 mts', cantidad: 1, precioCompra: 322000, distribuidor: null, precioVenta: 370000 },
    { nombre: 'Alambre puas 12.5 X 200 mts', cantidad: 1, precioCompra: 187000, distribuidor: null, precioVenta: 215000 },
    { nombre: 'chunky cachorro libra', cantidad: 10, precioCompra: 4775, distribuidor: null, precioVenta: 5300 },
    { nombre: 'chunky sobres', cantidad: 12, precioCompra: 2644, distribuidor: null, precioVenta: 3000 },
    { nombre: 'llaveros animales bogota', cantidad: 9, precioCompra: 10000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'Estuche navaja de castrar', cantidad: 3, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'Estuche cuero celular grande', cantidad: 3, precioCompra: 12000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'estuche cuero celular pequeño', cantidad: 1, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'estuche navaja normal', cantidad: 2, precioCompra: 12000, distribuidor: null, precioVenta: 14000 },
    { nombre: 'portacuchillos', cantidad: 3, precioCompra: 40000, distribuidor: null, precioVenta: 50000 },
    { nombre: 'llaveros pistola', cantidad: 6, precioCompra: 3000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'galgocal tableta x 200 tableta', cantidad: 10, precioCompra: 2000, distribuidor: null, precioVenta: 4000 },
    { nombre: 'derrivon sobre', cantidad: 99, precioCompra: 2520, distribuidor: null, precioVenta: 5500 },
    { nombre: 'Ringo cachorro x kilo', cantidad: 30, precioCompra: 4966, distribuidor: null, precioVenta: 5500 },
    { nombre: 'cuerda matizada X 500 mts #6', cantidad: 450, precioCompra: 770, distribuidor: null, precioVenta: 1200 },
    { nombre: 'Azul de metileno sobre', cantidad: 32, precioCompra: 6700, distribuidor: null, precioVenta: 8000 },
    { nombre: 'Nexabet ungüento', cantidad: 6, precioCompra: 16000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'curagan spray X 375 ml', cantidad: 9, precioCompra: 28166, distribuidor: null, precioVenta: 33500 },
    { nombre: 'vitamina K X 50 ml', cantidad: 9, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'vitamina K X 10 ml', cantidad: 10, precioCompra: 40400, distribuidor: null, precioVenta: 45000 },
    { nombre: 'garrabaño X 33 ml repuesto', cantidad: 14, precioCompra: 9542, distribuidor: null, precioVenta: 13500 },
    { nombre: 'profen 50 ml', cantidad: 4, precioCompra: 52371, distribuidor: null, precioVenta: 60500 },
    { nombre: 'profen 10 ml', cantidad: 8, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'chunky adulto libra', cantidad: 10, precioCompra: 3578, distribuidor: null, precioVenta: 4800 },
    { nombre: 'italcan perros kilo', cantidad: 30, precioCompra: 3666, distribuidor: null, precioVenta: 4800 },
    { nombre: 'quinocal tabletas', cantidad: 50, precioCompra: 310, distribuidor: null, precioVenta: 800 },
    { nombre: 'dectoplus 3.15% X 100 ml', cantidad: 2, precioCompra: 107900, distribuidor: null, precioVenta: 125000 },
    { nombre: 'Nex platino X 50 ml', cantidad: 1, precioCompra: 30400, distribuidor: null, precioVenta: 40000 },
    { nombre: 'dexapen 20 ml', cantidad: 2, precioCompra: 28500, distribuidor: null, precioVenta: 38000 },
    { nombre: 'trimediazina 50 ml', cantidad: 8, precioCompra: 37422, distribuidor: null, precioVenta: 42000 },
    { nombre: 'alvendavem 100', cantidad: 11, precioCompra: 16971, distribuidor: null, precioVenta: 23000 },
    { nombre: 'hemopar 30 ml', cantidad: 1, precioCompra: 22100, distribuidor: null, precioVenta: 29000 },
    { nombre: 'machetas solas', cantidad: 13, precioCompra: 22000, distribuidor: null, precioVenta: 25000 },
    { nombre: 'funda rabo de gallo angosta', cantidad: 10, precioCompra: 23000, distribuidor: null, precioVenta: 30000 },
    { nombre: 'funda rabo de gallo ancha', cantidad: 5, precioCompra: 30000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'Depoprovera ampolla x cm', cantidad: 6, precioCompra: 8933, distribuidor: null, precioVenta: 18000 },
    { nombre: 'bolsas de café x 100', cantidad: 12, precioCompra: 2400, distribuidor: null, precioVenta: 2800 },
    { nombre: 'finpronil jeringa', cantidad: 12, precioCompra: 4000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'fundas 4 puntas brillantes negras', cantidad: 3, precioCompra: 19500, distribuidor: null, precioVenta: 28000 },
    { nombre: 'macheta collis #20 verde', cantidad: 1, precioCompra: 15500, distribuidor: null, precioVenta: 18500 },
    { nombre: 'qdican gatos libra', cantidad: 23, precioCompra: 5000, distribuidor: null, precioVenta: 5800 },
    { nombre: 'cuelleros', cantidad: 17, precioCompra: 6000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'Cutamycom crema x 35 grs', cantidad: 4, precioCompra: 21600, distribuidor: null, precioVenta: 28000 },
    { nombre: 'bebedero aves 2 litros', cantidad: 2, precioCompra: 12200, distribuidor: null, precioVenta: 15500 },
    { nombre: 'bebedero aves 8 litros', cantidad: 1, precioCompra: 20000, distribuidor: null, precioVenta: 26000 },
    { nombre: 'comedero aves 12 kg', cantidad: 1, precioCompra: 20400, distribuidor: null, precioVenta: 27000 },
    { nombre: 'PUNTILLAS 2 1/2 X 500 grs', cantidad: 12, precioCompra: 4580, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Puntillas 3 X 9 X 500 grs', cantidad: 12, precioCompra: 4580, distribuidor: null, precioVenta: 7000 },
    { nombre: 'iventrina 250 ml', cantidad: 15, precioCompra: 12125, distribuidor: null, precioVenta: 18000 },
    { nombre: 'iventrina litro', cantidad: 2, precioCompra: 25705, distribuidor: null, precioVenta: 37000 },
    { nombre: 'plastico calibre 8 X 6 X 70 mts', cantidad: 70, precioCompra: 8700, distribuidor: null, precioVenta: 10500 },
    { nombre: 'oxitetraciclina X 50 ml X 50', cantidad: 9, precioCompra: 10600, distribuidor: null, precioVenta: 14500 },
    { nombre: 'albentrex jeringa x 20 ml', cantidad: 12, precioCompra: 7200, distribuidor: null, precioVenta: 10500 },
    { nombre: 'Bebederos 5 litros', cantidad: 4, precioCompra: 14600, distribuidor: null, precioVenta: 18500 },
    { nombre: 'comederos 3 kg', cantidad: 5, precioCompra: 12200, distribuidor: null, precioVenta: 15800 },
    { nombre: 'comederos 7 kg', cantidad: 1, precioCompra: 16600, distribuidor: null, precioVenta: 22000 },
    { nombre: 'sinchas fique', cantidad: 6, precioCompra: 15000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'mangas tela', cantidad: 12, precioCompra: 4000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'canastos cafeteros medianos', cantidad: 1, precioCompra: 25000, distribuidor: null, precioVenta: 32000 },
    { nombre: 'canastos cafeteros grandes', cantidad: 8, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'glicocafe 4 litros', cantidad: 3, precioCompra: 70500, distribuidor: null, precioVenta: 77000 },
    { nombre: 'vacuna biobac 11 vias 20 DS (100 ML)', cantidad: 14, precioCompra: 31000, distribuidor: null, precioVenta: 40000 },
    { nombre: 'vacuna biobac 7 vias X 10 DS 50 ML', cantidad: 6, precioCompra: 8000, distribuidor: null, precioVenta: 12000 },
    { nombre: 'albendavem 25% X 500', cantidad: 6, precioCompra: 77100, distribuidor: null, precioVenta: 85000 },
    { nombre: 'oxitetraciclina 200 MK X 50 ml', cantidad: 10, precioCompra: 21700, distribuidor: null, precioVenta: 27000 },
    { nombre: 'complemild oral X 100 ml', cantidad: 7, precioCompra: 7100, distribuidor: null, precioVenta: 10000 },
    { nombre: 'amprodiar sobre', cantidad: 29, precioCompra: 9700, distribuidor: null, precioVenta: 13000 },
    { nombre: 'Quinocal tabletas unidad', cantidad: 72, precioCompra: 716, distribuidor: null, precioVenta: 900 },
    { nombre: 'servimeg gold x 50 ml', cantidad: 3, precioCompra: 24600, distribuidor: null, precioVenta: 29000 },
    { nombre: 'trevesec 30 ml + compelnd 20 ml', cantidad: 1, precioCompra: 33600, distribuidor: null, precioVenta: 44000 },
    { nombre: 'trevesec 50 ml + compelnd 50 ml', cantidad: 1, precioCompra: 57300, distribuidor: null, precioVenta: 65000 },
    { nombre: 'vacuna ultrachoice x 10 DS', cantidad: 8, precioCompra: 15000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'vitazoo 500 ml', cantidad: 3, precioCompra: 18400, distribuidor: null, precioVenta: 24000 },
    { nombre: 'dextromin 500 ml', cantidad: 2, precioCompra: 17000, distribuidor: null, precioVenta: 23000 },
    { nombre: 'aguja metalica unidad', cantidad: 48, precioCompra: 1300, distribuidor: null, precioVenta: 2000 },
    { nombre: 'jeringa plastica 20 ml', cantidad: 2, precioCompra: 30000, distribuidor: null, precioVenta: 38000 },
    { nombre: 'jeringa plastica 10 ml', cantidad: 1, precioCompra: 30000, distribuidor: null, precioVenta: 38000 },
    { nombre: 'Espiramicina promevet', cantidad: 6, precioCompra: 29500, distribuidor: null, precioVenta: 35500 },
    { nombre: 'diarrevet sobre', cantidad: 48, precioCompra: 3600, distribuidor: null, precioVenta: 5500 },
    { nombre: 'bolfo sobres X 20 grs', cantidad: 3, precioCompra: 5200, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Damasgan 50 ml', cantidad: 1, precioCompra: 20000, distribuidor: null, precioVenta: 26000 },
    { nombre: 'tela verde x mts', cantidad: 80, precioCompra: 2000, distribuidor: null, precioVenta: 2500 },
    { nombre: 'forros celular cuero', cantidad: 7, precioCompra: 12000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'forros celular cuero pequeños', cantidad: 4, precioCompra: 7500, distribuidor: null, precioVenta: 10000 },
    { nombre: 'forros celular deportivos', cantidad: 3, precioCompra: 12000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'forros de cierre', cantidad: 2, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'collares perros peluches', cantidad: 5, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'collares perros medianos completos', cantidad: 8, precioCompra: 12000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'cuellos con peluches flores', cantidad: 11, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'cuellos 348', cantidad: 10, precioCompra: 3000, distribuidor: null, precioVenta: 5000 },
    { nombre: 'cuellos medianos', cantidad: 10, precioCompra: 3500, distribuidor: null, precioVenta: 5000 },
    { nombre: 'lorsban papeleta', cantidad: 17, precioCompra: 1000, distribuidor: null, precioVenta: 2000 },
    { nombre: 'guantes negros pepas', cantidad: 12, precioCompra: 1300, distribuidor: null, precioVenta: 2500 },
    { nombre: 'cinta de moscas', cantidad: 3, precioCompra: 1000, distribuidor: null, precioVenta: 1500 },
    { nombre: 'vacuna neumodiar repuesto', cantidad: 24, precioCompra: 5700, distribuidor: null, precioVenta: 9000 },
    { nombre: 'ivermectina 3.15% 100 ml', cantidad: 5, precioCompra: 31800, distribuidor: null, precioVenta: 41000 },
    { nombre: 'isovex hormiga', cantidad: 2, precioCompra: 19500, distribuidor: null, precioVenta: 25000 },
    { nombre: 'lactoremplazador libra', cantidad: 11, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'champus perros reempados 120 ml', cantidad: 12, precioCompra: 7000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'champu perros reempados 60 ml', cantidad: 5, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'Impulsor 500 ml', cantidad: 2, precioCompra: 157000, distribuidor: null, precioVenta: 180000 },
    { nombre: 'oxitetraciclina MK X 500 ml', cantidad: 1, precioCompra: 45900, distribuidor: null, precioVenta: 58000 },
    { nombre: 'ivermen dorado 3.15% x 250 ml', cantidad: 10, precioCompra: 66400, distribuidor: null, precioVenta: 86500 },
    { nombre: 'ivermen dorado 3.15% X 500 ml', cantidad: 1, precioCompra: 121700, distribuidor: null, precioVenta: 158000 },
    { nombre: 'servimeg gold X 500 ml', cantidad: 3, precioCompra: 128200, distribuidor: null, precioVenta: 167000 },
    { nombre: 'depoprovera dosis', cantidad: 15, precioCompra: 9000, distribuidor: null, precioVenta: 18000 },
    { nombre: 'sales de hidratacion oral sobre', cantidad: 22, precioCompra: 1600, distribuidor: null, precioVenta: 3000 },
    { nombre: 'panzer litro', cantidad: 15, precioCompra: 19400, distribuidor: null, precioVenta: 24500 },
    { nombre: 'manzate x kg', cantidad: 12, precioCompra: 26500, distribuidor: null, precioVenta: 29500 },
    { nombre: 'pilarsato litro', cantidad: 12, precioCompra: 16600, distribuidor: null, precioVenta: 22000 },
    { nombre: 'glicocafe litro', cantidad: 15, precioCompra: 17000, distribuidor: null, precioVenta: 22000 },
    { nombre: 'alfombras', cantidad: 1, precioCompra: 25000, distribuidor: null, precioVenta: 35000 },
    { nombre: 'levanter levamiso cojin', cantidad: 102, precioCompra: 2700, distribuidor: null, precioVenta: 3800 },
    { nombre: 'oxitoxina 10 ml', cantidad: 8, precioCompra: 5600, distribuidor: null, precioVenta: 8500 },
    { nombre: 'fosfoland 50 ml', cantidad: 8, precioCompra: 30000, distribuidor: null, precioVenta: 36000 },
    { nombre: 'fosfoland 20 ml repuesto', cantidad: 5, precioCompra: 20000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'enrofloxacina gotas 10 ml', cantidad: 25, precioCompra: 500, distribuidor: null, precioVenta: 8500 },
    { nombre: 'baticolas caballos', cantidad: 6, precioCompra: 25000, distribuidor: null, precioVenta: 28000 },
    { nombre: 'canapets pupy 2ml', cantidad: 12, precioCompra: 4500, distribuidor: null, precioVenta: 6500 },
    { nombre: 'canapets pupy 5ml', cantidad: 7, precioCompra: 5400, distribuidor: null, precioVenta: 7000 },
    { nombre: 'piperazina pastilla', cantidad: 242, precioCompra: 1083, distribuidor: null, precioVenta: 1500 },
    { nombre: 'cancun 300 ml', cantidad: 9, precioCompra: 8000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'cancun 500 ml', cantidad: 8, precioCompra: 11000, distribuidor: null, precioVenta: 15000 },
    { nombre: 'cipertop 375 ml', cantidad: 6, precioCompra: 18209, distribuidor: null, precioVenta: 30000 },
    { nombre: 'tusivet 120 ml', cantidad: 3, precioCompra: 13418, distribuidor: null, precioVenta: 18500 },
    { nombre: 'canatox 20 ml', cantidad: 3, precioCompra: 19507, distribuidor: null, precioVenta: 28000 },
    { nombre: 'talco can amor insecticida', cantidad: 2, precioCompra: 18542, distribuidor: null, precioVenta: 20500 },
    { nombre: 'jeringa plastica X 10 ml', cantidad: 2, precioCompra: 21320, distribuidor: null, precioVenta: 30000 },
    { nombre: 'ungüento 100 X 50 grs', cantidad: 11, precioCompra: 8908, distribuidor: null, precioVenta: 12500 },
    { nombre: 'dipromid 10 ml', cantidad: 3, precioCompra: 20484, distribuidor: null, precioVenta: 29000 },
    { nombre: 'compleland oral X 100 ml', cantidad: 7, precioCompra: 7977, distribuidor: null, precioVenta: 10500 },
    { nombre: 'collar pechera con bolso', cantidad: 3, precioCompra: 14500, distribuidor: null, precioVenta: 18000 },
    { nombre: 'collar pechera', cantidad: 3, precioCompra: 17000, distribuidor: null, precioVenta: 20000 },
    { nombre: 'cuellos medianos mascotas', cantidad: 2, precioCompra: 4000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'collar BMR 5111', cantidad: 7, precioCompra: 7000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'collar 5177 completo', cantidad: 6, precioCompra: 4000, distribuidor: null, precioVenta: 8000 },
    { nombre: 'collares conejo', cantidad: 6, precioCompra: 4000, distribuidor: null, precioVenta: 6000 },
    { nombre: 'cuellos riata grandes', cantidad: 3, precioCompra: 10000, distribuidor: null, precioVenta: 13000 },
    { nombre: 'cuellos riata gris', cantidad: 5, precioCompra: 6000, distribuidor: null, precioVenta: 8000 },
    { nombre: 'cuellos riata mediana', cantidad: 16, precioCompra: 4000, distribuidor: null, precioVenta: 5000 },
    { nombre: 'cuello riata militar', cantidad: 3, precioCompra: 8000, distribuidor: null, precioVenta: 10000 },
    { nombre: 'cuello conejo pequeño', cantidad: 7, precioCompra: 3000, distribuidor: null, precioVenta: 5000 },
    { nombre: 'pañoletas perros', cantidad: 4, precioCompra: 2500, distribuidor: null, precioVenta: 3500 },
    { nombre: 'cuellos delgados sonajero', cantidad: 50, precioCompra: 1500, distribuidor: null, precioVenta: 2500 },
    { nombre: 'bozal', cantidad: 2, precioCompra: 5000, distribuidor: null, precioVenta: 7000 },
    { nombre: 'lazos con argolla blancos x 25 mts', cantidad: 2, precioCompra: 60000, distribuidor: null, precioVenta: 75000 },
    { nombre: 'maiz vermifugo', cantidad: 100, precioCompra: 430, distribuidor: null, precioVenta: 600 },
    { nombre: 'semiponchos', cantidad: 5, precioCompra: 18000, distribuidor: null, precioVenta: 22000 },
    { nombre: 'complebet 250 ml', cantidad: 3, precioCompra: 42500, distribuidor: null, precioVenta: 52000 },
    { nombre: 'alvendavem 500 ml', cantidad: 6, precioCompra: 39600, distribuidor: null, precioVenta: 85000 },
  ];

  console.log(`📦 Creando ${inventarioReal.length} productos...`);

  let created = 0;
  for (const item of inventarioReal) {
    if (!item.cantidad || item.cantidad <= 0) continue;
    
    const producto = await prisma.producto.create({
      data: {
        nombre: item.nombre,
        categoriaId: getCatId(item.nombre),
        precioCompra: item.precioCompra || 0,
        precioVenta: item.precioVenta || 0,
        stockMinimo: 5,
        unidadMedida: 'unidades',
        activo: true,
      },
    });

    // Crear inventario actual
    await prisma.inventarioActual.create({
      data: {
        productoId: producto.id,
        cantidadActual: item.cantidad,
      },
    });

    created++;
  }

  console.log(`✅ ${created} productos creados con su inventario`);

  // Verificar usuario admin
  const adminExists = await prisma.user.findUnique({ where: { email: 'admin@veterinaria.com' } });
  if (!adminExists) {
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await prisma.user.create({
      data: {
        email: 'admin@veterinaria.com',
        password: hashedPassword,
        nombre: 'Administrador',
        rol: 'ADMIN',
      },
    });
    console.log('✅ Usuario admin creado');
  }

  console.log('🎉 ¡Datos reales cargados exitosamente!');
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
